In [1]:
import numpy as np

a = np.array([[1,2], [3,4]])
a.flatten()

array([1, 2, 3, 4])

In [2]:
a.flatten()[:, None]

array([[1],
       [2],
       [3],
       [4]])

In [3]:
a.flatten().shape

(4,)

In [4]:
a.flatten()[:, None].shape

(4, 1)

In [6]:
import scipy.io

data = scipy.io.loadmat('../Data/burgers_sine.mat')
data

{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Mon Jan 15 19:50:44 2018',
 '__version__': '1.0',
 '__globals__': [],
 't': array([[ 0.  ,  0.05,  0.1 ,  0.15,  0.2 ,  0.25,  0.3 ,  0.35,  0.4 ,
          0.45,  0.5 ,  0.55,  0.6 ,  0.65,  0.7 ,  0.75,  0.8 ,  0.85,
          0.9 ,  0.95,  1.  ,  1.05,  1.1 ,  1.15,  1.2 ,  1.25,  1.3 ,
          1.35,  1.4 ,  1.45,  1.5 ,  1.55,  1.6 ,  1.65,  1.7 ,  1.75,
          1.8 ,  1.85,  1.9 ,  1.95,  2.  ,  2.05,  2.1 ,  2.15,  2.2 ,
          2.25,  2.3 ,  2.35,  2.4 ,  2.45,  2.5 ,  2.55,  2.6 ,  2.65,
          2.7 ,  2.75,  2.8 ,  2.85,  2.9 ,  2.95,  3.  ,  3.05,  3.1 ,
          3.15,  3.2 ,  3.25,  3.3 ,  3.35,  3.4 ,  3.45,  3.5 ,  3.55,
          3.6 ,  3.65,  3.7 ,  3.75,  3.8 ,  3.85,  3.9 ,  3.95,  4.  ,
          4.05,  4.1 ,  4.15,  4.2 ,  4.25,  4.3 ,  4.35,  4.4 ,  4.45,
          4.5 ,  4.55,  4.6 ,  4.65,  4.7 ,  4.75,  4.8 ,  4.85,  4.9 ,
          4.95,  5.  ,  5.05,  5.1 ,  5.15,  5.2 ,  5.25,  5.3 ,

In [8]:
data['t'].shape

(1, 201)

In [9]:
data['t'].flatten().shape

(201,)

In [10]:
data['t'].flatten()[:, None].shape

(201, 1)

In [11]:
data['usol']

array([[ 1.22464680e-16,  1.26938691e-16,  6.76111706e-17, ...,
        -8.59426130e-19,  2.72425004e-18,  2.57275432e-18],
       [ 2.45412285e-02,  2.40509340e-02,  2.35804744e-02, ...,
         4.98764787e-03,  4.96778752e-03,  4.94808500e-03],
       [ 4.90676743e-02,  4.80881999e-02,  4.71482899e-02, ...,
         9.97526556e-03,  9.93554533e-03,  9.89614075e-03],
       ...,
       [-7.35645636e-02, -7.20981362e-02, -7.06907921e-02, ...,
        -1.49628229e-02, -1.49032437e-02, -1.48441380e-02],
       [-4.90676743e-02, -4.80881999e-02, -4.71482899e-02, ...,
        -9.97526556e-03, -9.93554533e-03, -9.89614075e-03],
       [-2.45412285e-02, -2.40509340e-02, -2.35804744e-02, ...,
        -4.98764787e-03, -4.96778752e-03, -4.94808500e-03]])

In [12]:
data['usol'] == np.real(data['usol'])

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [13]:
data['usol'].shape

(256, 201)

In [15]:
data['x'].flatten()[:, None].shape

(256, 1)

In [17]:
T, X = np.meshgrid(data['t'].flatten()[:, None], data['x'].flatten()[:, None])

In [18]:
T.shape

(256, 201)

In [21]:
XX = np.hstack(([1, 2], [3, 4]))
XX

array([1, 2, 3, 4])